### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by xtrinch** [bfaulk96/craco-mf#1]
Firstly thanks for this fork,

could you perhaps add a section in readme on how to 
- bundle the example code for production usage?

Regards

**Comment by bfaulk96** [comment]
Honestly I'm not entirely sure what you mean. I actually haven't personally used the example in this repo; I simply forked it to make it run. 😅 

If you'd be open to further explaining, I'm certainly open to adding some better docs!

**Comment by xtrinch** [comment]
I dove in the details since then and managed to create an example repo with some docker setup and an explanation for how to deploy to S3 https://github.com/xtrinch/create-react-app-module-federation-example
Thank you though :-)
